In [372]:
import pandas as pd
import numpy as np

In [373]:
df = pd.read_csv('../EDA_values.csv')
df.shape

C:\Users\Bruce\AppData\Local\Temp\ipykernel_17148\1271035946.py:1: DtypeWarning: Columns (2,5,6,7,8,10,12,13,15,48,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../EDA_values.csv')


(1048575, 55)

# Remove speed-limit=777, 888, 999, Blanks

In [374]:
outlier_speeds = [777,888,999]
df = df.dropna(subset=['speed_limit'])
df = df[df.speed_limit.isin(outlier_speeds) == False]
df['speed_limit'].unique()

array([60, 40, 100, 50, 80, 70, 90, 25, 110, 15, 10, 20, 30, 5, 75, '50',
       '100', '80', '90', '60', '40', '70', '30', '20', '110', '10',
       '100 - 110 km/h', '60 km/h', '0 - 50 km/h', '70 km/h',
       '80 - 90 km/h'], dtype=object)

# Change string speeds to numeric

In [375]:
df.loc[df['speed_limit'] == '0 - 50 km/h', 'speed_limit'] = 50
df.loc[df['speed_limit'] == '60 km/h', 'speed_limit'] = 60
df.loc[df['speed_limit'] == '70 km/h', 'speed_limit'] = 70
df.loc[df['speed_limit'] == '80 - 90 km/h', 'speed_limit'] = 90
df.loc[df['speed_limit'] == '100 - 110 km/h', 'speed_limit'] = 100
df['speed_limit']=pd.to_numeric(df.speed_limit).astype(np.int64)
df['speed_limit'].unique()

array([ 60,  40, 100,  50,  80,  70,  90,  25, 110,  15,  10,  20,  30,
         5,  75], dtype=int64)

# Change speed limit to categorical using new speed_labels column
### 0-50 km/h, 50-80 km/h, 80-100 km/h, 100+ km/h

In [376]:
speed_labels = pd.cut(x=df['speed_limit'], bins=[0, 50, 80, 90, 999],
                    labels=['0-50 km/h', '50-80 km/h', '80-100 km/h',
                             '100+ km/h'])
df.insert(loc = 2, column = 'speed_labels', value = speed_labels)
df['speed_labels'].unique()

['50-80 km/h', '0-50 km/h', '100+ km/h', '80-100 km/h']
Categories (4, object): ['0-50 km/h' < '50-80 km/h' < '80-100 km/h' < '100+ km/h']

# Remove road_position horizontal and vertical, road_sealed, road_wet

In [377]:
df.drop(['road_position_horizontal', 'road_position_vertical', 'road_sealed', 'road_wet'], axis=1, inplace=True)
df.columns

Index(['description_id', 'severity', 'speed_labels', 'speed_limit', 'midblock',
       'intersection', 'weather', 'crash_type', 'lighting', 'traffic_controls',
       'drugs_alcohol', 'DCA_code', 'comment', 'vehicles_id', 'animals',
       'car_sedan', 'car_utility', 'car_van', 'car_4x4', 'car_station_wagon',
       'motor_cycle', 'truck_small', 'truck_large', 'bus', 'taxi', 'bicycle',
       'scooter', 'pedestrian', 'inanimate', 'train', 'tram', 'vehicle_other',
       'date_time_id', 'year', 'month', 'day_of_week', 'day_of_month', 'hour',
       'approximate', 'lat_long', 'latitude', 'longitude', 'country', 'state',
       'local_government_area', 'statistical_area', 'suburb', 'casualties_id',
       'casualties', 'fatalities', 'serious_injuries', 'minor_injuries'],
      dtype='object')

# Remove weather=unknown

In [378]:
weather_outliers = ['unknown']
df = df[df.weather.isin(weather_outliers) == False]
df['weather'].unique()

array(['fine', 'rain', 'smoke_dust', 'high_wind', 'fog', 'snow', 'mist'],
      dtype=object)

# Remove lighting=unknown, other

In [379]:
lighting_outliers = ['unknown']
df = df[df.lighting.isin(lighting_outliers) == False]
df['lighting'].unique()

array(['daylight', 'darkness_not_lit', 'darkness_lit', 'dawn_dusk',
       'other'], dtype=object)

# Remove traffic_controls=other, blank

In [380]:
traffic_outliers = ['other', 'none']
df = df[df.traffic_controls.isin(traffic_outliers) == False]
df = df.dropna(subset=['traffic_controls'])
df['traffic_controls'].unique()

array(['stop_sign', 'traffic_lights', 'giveway_sign', 'railway_crossing',
       'manual_control', 'school_crossing', 'pedestrian_crossing'],
      dtype=object)

# Drug_alcohol change blank to 0 and 'Y' to 1

In [381]:
df['drugs_alcohol'] = df['drugs_alcohol'].fillna(False)
df.loc[df['drugs_alcohol'] == 'Y', 'drugs_alcohol'] = True
df['drugs_alcohol'] = df['drugs_alcohol'].astype(bool)
df['drugs_alcohol'].unique()

array([False,  True])

# DCA code important, unsure how to continue
### Removing column for now

In [382]:
df.drop(['DCA_code'], axis=1, inplace=True)
df.columns

Index(['description_id', 'severity', 'speed_labels', 'speed_limit', 'midblock',
       'intersection', 'weather', 'crash_type', 'lighting', 'traffic_controls',
       'drugs_alcohol', 'comment', 'vehicles_id', 'animals', 'car_sedan',
       'car_utility', 'car_van', 'car_4x4', 'car_station_wagon', 'motor_cycle',
       'truck_small', 'truck_large', 'bus', 'taxi', 'bicycle', 'scooter',
       'pedestrian', 'inanimate', 'train', 'tram', 'vehicle_other',
       'date_time_id', 'year', 'month', 'day_of_week', 'day_of_month', 'hour',
       'approximate', 'lat_long', 'latitude', 'longitude', 'country', 'state',
       'local_government_area', 'statistical_area', 'suburb', 'casualties_id',
       'casualties', 'fatalities', 'serious_injuries', 'minor_injuries'],
      dtype='object')

# Remove comments, vehicle_id, vehicle_other

In [383]:
df.drop(['comment', 'vehicles_id', 'vehicle_other'], axis=1, inplace=True)
df.columns

Index(['description_id', 'severity', 'speed_labels', 'speed_limit', 'midblock',
       'intersection', 'weather', 'crash_type', 'lighting', 'traffic_controls',
       'drugs_alcohol', 'animals', 'car_sedan', 'car_utility', 'car_van',
       'car_4x4', 'car_station_wagon', 'motor_cycle', 'truck_small',
       'truck_large', 'bus', 'taxi', 'bicycle', 'scooter', 'pedestrian',
       'inanimate', 'train', 'tram', 'date_time_id', 'year', 'month',
       'day_of_week', 'day_of_month', 'hour', 'approximate', 'lat_long',
       'latitude', 'longitude', 'country', 'state', 'local_government_area',
       'statistical_area', 'suburb', 'casualties_id', 'casualties',
       'fatalities', 'serious_injuries', 'minor_injuries'],
      dtype='object')

# Categorize severity

In [384]:
df['severity'] = df['severity'] = pd.Categorical(df.severity)
df['severity'].unique()

['property_damage', 'minor_injury', 'serious_injury', 'fatality']
Categories (4, object): ['fatality', 'minor_injury', 'property_damage', 'serious_injury']

# Categorize weather, lighting, and traffic controls

In [385]:
df['weather'] = df['weather'] = pd.Categorical(df.weather)
df['lighting'] = df['lighting'] = pd.Categorical(df.lighting)
df['traffic_controls'] = df['traffic_controls'] = pd.Categorical(df.traffic_controls)
print(df['weather'].unique())
print(df['lighting'].unique())
print(df['traffic_controls'].unique())

['fine', 'rain', 'snow', 'mist', 'fog', 'smoke_dust']
Categories (6, object): ['fine', 'fog', 'mist', 'rain', 'smoke_dust', 'snow']
['daylight', 'darkness_not_lit', 'dawn_dusk', 'darkness_lit']
Categories (4, object): ['darkness_lit', 'darkness_not_lit', 'dawn_dusk', 'daylight']
['stop_sign', 'traffic_lights', 'giveway_sign', 'railway_crossing', 'manual_control', 'school_crossing', 'pedestrian_crossing']
Categories (7, object): ['giveway_sign', 'manual_control', 'pedestrian_crossing', 'railway_crossing', 'school_crossing', 'stop_sign', 'traffic_lights']


# Compare severity vs datetime columns and decide what to do with those columns
### Unsure of severity correlation with date time so those columns were removed for now

In [386]:
df.drop(['year', 'month','day_of_week', 'day_of_month', 'hour'], axis=1, inplace=True)
df.columns

Index(['description_id', 'severity', 'speed_labels', 'speed_limit', 'midblock',
       'intersection', 'weather', 'crash_type', 'lighting', 'traffic_controls',
       'drugs_alcohol', 'animals', 'car_sedan', 'car_utility', 'car_van',
       'car_4x4', 'car_station_wagon', 'motor_cycle', 'truck_small',
       'truck_large', 'bus', 'taxi', 'bicycle', 'scooter', 'pedestrian',
       'inanimate', 'train', 'tram', 'date_time_id', 'approximate', 'lat_long',
       'latitude', 'longitude', 'country', 'state', 'local_government_area',
       'statistical_area', 'suburb', 'casualties_id', 'casualties',
       'fatalities', 'serious_injuries', 'minor_injuries'],
      dtype='object')

# Remove description_id, date_time_id, crash_type, approximate to minor_injuries columns

In [387]:
df.drop(['description_id', 'date_time_id', 'crash_type','approximate', 'lat_long',
         'latitude', 'longitude', 'country', 'state', 'local_government_area',
         'statistical_area', 'suburb', 'casualties_id', 'casualties',
         'fatalities', 'serious_injuries', 'minor_injuries'], axis=1, inplace=True)
df.columns

Index(['severity', 'speed_labels', 'speed_limit', 'midblock', 'intersection',
       'weather', 'lighting', 'traffic_controls', 'drugs_alcohol', 'animals',
       'car_sedan', 'car_utility', 'car_van', 'car_4x4', 'car_station_wagon',
       'motor_cycle', 'truck_small', 'truck_large', 'bus', 'taxi', 'bicycle',
       'scooter', 'pedestrian', 'inanimate', 'train', 'tram'],
      dtype='object')

# Final shape and data types

In [388]:
print(df.shape)
print(df.dtypes)

(287947, 26)
severity             category
speed_labels         category
speed_limit             int64
midblock                 bool
intersection             bool
weather              category
lighting             category
traffic_controls     category
drugs_alcohol            bool
animals                 int64
car_sedan               int64
car_utility             int64
car_van                 int64
car_4x4                 int64
car_station_wagon       int64
motor_cycle             int64
truck_small             int64
truck_large             int64
bus                     int64
taxi                    int64
bicycle                 int64
scooter                 int64
pedestrian              int64
inanimate               int64
train                   int64
tram                    int64
dtype: object


# Export to CSV

In [389]:
df.to_csv('./Data_Cleaning_output.csv')